### PR TITLE
Fix troyka modules

### PR DESCRIPTION
**Pull request by alinkacxt**
Добавила платы:
- [AMP-B002] troyka-temperature-sensor
- [AMP-B003] troyka-potentiometer
- [AMP-B004] troyka-light-sensor
- [AMP-B005] troyka-led-module-R, G, B, W, Y
- [AMP-B006] troyka-ir-receiver
- [AMP-B007] troyka-hall-sensor
- [AMP-B008] troyka-buzzer
- [AMP-B009] troyka-button
- [AMP-B010] troyka-relay
- [AMP-B012] analog-line-sensor
- [AMP-B018]  digital-line-sensor
- [AMP-B022] troyka-tilt-sensor
- [AMP-B026] troyka-dc-dc-booster
- [AMP-B028] troyka-stepper-motor-driver
- [AMP-B039] iskra-mini
- [AMP-B040] iskra-mini-headless
- [AMP-B043] troyka-rtc
- [AMP-B045] troyka-temperature-humidity-sensor-dht11
- [AMP-B048] troyka-3d-joystick
- [AMP-B058] troyka-rfid-nfc-1356
- [AMP-B062] troyka-5mm-led-module - R, G, B, W, Y
- [AMP-B063] troyka-current-sensor
- [AMP-B064] troyka-rs485
- [AMP-B066] troyka-mini-relay
- [AMP-B072]  troyka-proximity
- [AMP-B074] troyka-line-in-mini-jack
- [AMP-B075] troyka-line-out-mini-jack
- [AMP-B091] troyka-vibration-sensor.

### CODE REVIEW

**Review by igor605ds — COMMENTED** [review]
Всё круто! 
Ниже список модулей, где нужно внести мелкие изменения:
- [AMP-B007] troyka-hall-sensor
- [AMP-B008] troyka-buzzer
- [AMP-B010] troyka-relay
- [AMP-B026] troyka-dc-dc-booster
- [AMP-B028] troyka-stepper-motor-driver
- [AMP-B043] troyka-rtc
- [AMP-B091] troyka-vibration-sensor

**Comment by alinkacxt** [comment]
Смотри

**Review by igor605ds — APPROVED** [review]
👍 LGTM

**Comment by alinkacxt** [comment]
😇

**Pull request merged**
